url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "TQ Compendium" # the name of your site, e.g. ACME Corp.
description: ""
theme: minima
remote_theme: jekyll/minima
minima:
  skin: solarized
header_pages:
  - weapons.md
  - armour.md
  - shields.md
  - miscellaneous.md
  - skills.md