url: "https://toshesquest.com" # the base hostname & protocol for your site, e.g. http://example.com
title: "Toshe's Quest" # the name of your site, e.g. ACME Corp.
description: ""
theme: minima
remote_theme: jekyll/minima
minima:
  skin: solarized
header_pages:
  - how-to-play.md
  - compendium/welcome.html
author:
  name: Ben Gardner